const INITIALIZE = "INITIALIZE";
const CREATE_AUTHOR = "CREATE_AUTHOR";
const UPDATE_AUTHOR = "UPDATE_AUTHOR";
const DELETE_AUTHOR = "DELETE_AUTHOR";

export default {
  INITIALIZE,
  CREATE_AUTHOR,
  UPDATE_AUTHOR,
  DELETE_AUTHOR
};
